### ISSUE TITLE
Follow up

### ISSUE THREAD

**Issue by steveoh** [OpenSaltLake/OpenSaltLake_Website#1]
Hey folks, nice meeting you today. I was hoping to become a part of this organization and also join the slack channel. Would you mind sending me the link for the heroku app or an invitation? 

Thanks in advance,

Steve

**Comment by rachelintheworld** [comment]
Glad to have you, Steve!

Join the chatter on our Slack: http://bit.ly/oslslack

**Comment by steveoh** [comment]
thank you!

**Comment by todrobbins** [comment]
Welcome @steveoh!
